
name: codepipeline

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codepipeline
        uses: actions/checkout@v2

      - name: Install dependencies #work
        run: |
          cd Devops-challange\devops-ci-challenge\codebase\rdicidr-0.1.0\package.json
          npm install 

      - name: Lint 
        run: npm run prettier 

      - name: Test 
        run: CI=true npm run test 

      - name: Build 
        run: npm run build # this is a test run

       
